server:
  port: 9000

spring:
  application:
    name: security
  security:
    user:
      name: user
      password: password
    oauth2:
      authorizationServer:
        issuer: http://auth-server:9000
        client:
          api-client:
            registration:
              client-id: bff-client
              client-secret: "{noop}client_secret"
              client-name: bff Client
              client-authentication-methods:
                - client_secrets_basic
              authorization-grant-types:
                - authorization-code
                - refresh_token
              redirect-uris:
                - http://127.0.0.1:8080/login/oauth2/code/bff-client
                - http://127.0.0.1:8080/
              scopes:
                - openid
                - profile
                - read
            require-authorization-consent: true



logging:
  level:
    org:
      springframework:
        oauth2: DEBUG
        security: trace
