server:
  port: 9000

spring:
  application:
    name: security
  security:
    user:
      name: user
      password: password
    oauth2:
      authorizationServer:
        issuer: http://auth-server:9000
        client:
          api-client:
            registration:
              client-id: api-client
              client-secret: "{client_secret}"
              client-name: API Client
              client-authentication-methods:
                - client_secrets_basic
              authorization-grant-types:
                - authorization-code
                - refresh_token
              redirect-uris:
                - http://127.0.0.1:8080/login/oauth2/code/api-client
                - http://127.0.0.1:8080/
              scopes:
                - openid
                - profile
            require-authorization-consent: true



logging:
  level:
    org.springframework.security: trace